### ISSUE TITLE
Seque to Tabbar Controller

### ISSUE THREAD

**Issue by MartinQue** [vinit5320/AnimatedLogin#1]
I've been working on transitioning the button animation to a tabbar controller but no luck. Is there a way you can help me with this? Hw do i seque to the homeVC of my tabbar controller? 
Many thanks in advance :)

**Comment by FarisAlbalawi** [comment]
```
 let tbc = self.storyboard?.instantiateViewController(withIdentifier: "MainTabBar") as! UITabBarController
                tbc.selectedIndex = 0
                
                self.present(tbc, animated: false, completion: nil)
```
